### PR TITLE
Fix `isCircle` bug and some refactoring.

### LINKED ISSUE #53: Xcode 11 builds with 'type-check time limit exceeded' warnings
**Describe the bug**
Xcode 11 brings with it new joys and warnings. In this case, the Xcode 11.1 GM Seed (11A1027) turns on the 'type-check time limit' warning, which hopes to help us keep our compile times fast.

**To Reproduce**
1. Open project in Xcode 11.1.
2. Build
3. Look at warnings.

**Expected behavior**
No 'type-check time limit exceeded' warnings.

**Screenshots**
Screenshot 2019-10-01 at 14 04 42

**Expected solution**
Simplify more complex statements, adding additional type declarations. This should be doable without actually requiring Xcode 11.1.

### LINKED ISSUE #54: `UIView.isCircle` returns false when the view is a circle
**Describe the bug**
`UIView.isCircle` returns false when the view is actually a circle.

**To Reproduce**
1. Create UIView() with dimensions 10x10.
2. Set corner radius to 5.
3. Print result of `isCircle`.

**Expected behavior**
Prints `true`.

**Screenshots**
Screenshot 2019-10-01 at 14 11 54

### PR DESCRIPTION
**Pull request by SpacyRicochet**
Fixes #54.
Fixes #53 with a work-around.

I couldn't get the compile times of a couple of functions down enough, so instead I upped the time limit to the still reasonable value of 400 milliseconds. Let me know if this is objectionable.

### CODE REVIEW

File: SwiftIsland/Map/MapPolygon.swift [hunk 1]
```diff
@@ -28,27 +28,41 @@ final class MapPolygon: MKPolygonRenderer {
...
-    let text = "\(area.name)"
-    let font = UIFont.systemFont(ofSize: 50.0)
-    let attributes = [NSAttributedString.Key.paragraphStyle: paragraphStyle,
-                      NSAttributedString.Key.font: font,
-                      NSAttributedString.Key.foregroundColor: UIColor.themeColor(.redDark)]
-    let fontSize = text.size(withAttributes: attributes)
+    let attributes = textAttributes(with: UIFont.systemFont(ofSize: 50.0),
+                                    textAlignment: .center,
+                                    color: UIColor.themeColor(.redDark))
+    let text = NSString(string: "\(area.name)")
```
Comment (ppeelen) [inline SwiftIsland/Map/MapPolygon.swift]: We should not use `NSString`, we should use `String` instead. Since `String` is widely used in Swift and is a struct type, whereas `NSString` (although we can convert it seamlessly) comes from Objective-C and is a class, inheriting from `NSObject`. We should avoid using Objectiv-C types.
```suggestion
    let text = area.name
```

**Review by ppeelen — CHANGES_REQUESTED** [review]
Great work and some very nice improvements. Just had one minor comment which I hope you would like to fix.
⭐️⭐️⭐️

File: SwiftIsland/Map/MapPolygon.swift (hunk 1 above)
Comment (SpacyRicochet) [reply SwiftIsland/Map/MapPolygon.swift]: Sure. This was an attempt at appeasing the type checker, since `size(withAttributes:)` is an `NSString` method and not a `String` method. Declaring it as the Objective-C version would smooth that out a bit.

Now that we're stretching the time limit anyway that isn't necessary anymore.

**Review by ppeelen — APPROVED** [review]
